<?php
/**
 * ModelTypeApi
 * PHP version 5
 *
 * @category Class
 * @package  RadioManager
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * RadioManager
 *
 * RadioManager
 *
 * OpenAPI spec version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.0
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace RadioManager\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\Psr7\Query;
use GuzzleHttp\RequestOptions;
use RadioManager\ApiException;
use RadioManager\Configuration;
use RadioManager\HeaderSelector;
use RadioManager\ObjectSerializer;

/**
 * ModelTypeApi Class Doc Comment
 *
 * @category Class
 * @package  RadioManager
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ModelTypeApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getModelTypeById
     *
     * Get modelType by id
     *
     * @param  int $id ID of ModelType **(Required)** (required)
     * @param  int $_external_station_id Query on a different (content providing) station *(Optional)* (optional)
     *
     * @throws \RadioManager\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \RadioManager\Model\ModelTypeResult
     */
    public function getModelTypeById($id, $_external_station_id = null)
    {
        list($response) = $this->getModelTypeByIdWithHttpInfo($id, $_external_station_id);
        return $response;
    }

    /**
     * Operation getModelTypeByIdWithHttpInfo
     *
     * Get modelType by id
     *
     * @param  int $id ID of ModelType **(Required)** (required)
     * @param  int $_external_station_id Query on a different (content providing) station *(Optional)* (optional)
     *
     * @throws \RadioManager\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \RadioManager\Model\ModelTypeResult, HTTP status code, HTTP response headers (array of strings)
     */
    public function getModelTypeByIdWithHttpInfo($id, $_external_station_id = null)
    {
        $returnType = '\RadioManager\Model\ModelTypeResult';
        $request = $this->getModelTypeByIdRequest($id, $_external_station_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\RadioManager\Model\ModelTypeResult',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\RadioManager\Model\Forbidden',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\RadioManager\Model\NotFound',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\RadioManager\Model\TooManyRequests',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getModelTypeByIdAsync
     *
     * Get modelType by id
     *
     * @param  int $id ID of ModelType **(Required)** (required)
     * @param  int $_external_station_id Query on a different (content providing) station *(Optional)* (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getModelTypeByIdAsync($id, $_external_station_id = null)
    {
        return $this->getModelTypeByIdAsyncWithHttpInfo($id, $_external_station_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getModelTypeByIdAsyncWithHttpInfo
     *
     * Get modelType by id
     *
     * @param  int $id ID of ModelType **(Required)** (required)
     * @param  int $_external_station_id Query on a different (content providing) station *(Optional)* (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getModelTypeByIdAsyncWithHttpInfo($id, $_external_station_id = null)
    {
        $returnType = '\RadioManager\Model\ModelTypeResult';
        $request = $this->getModelTypeByIdRequest($id, $_external_station_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getModelTypeById'
     *
     * @param  int $id ID of ModelType **(Required)** (required)
     * @param  int $_external_station_id Query on a different (content providing) station *(Optional)* (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getModelTypeByIdRequest($id, $_external_station_id = null)
    {
        // verify the required parameter 'id' is set
        if ($id === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getModelTypeById'
            );
        }
        if ($id < 0) {
            throw new \InvalidArgumentException('invalid value for "$id" when calling ModelTypeApi.getModelTypeById, must be bigger than or equal to 0.');
        }


        $resourcePath = '/model_types/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($_external_station_id !== null) {
            $queryParams['_external_station_id'] = ObjectSerializer::toQueryValue($_external_station_id);
        }

        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api-key');
        if ($apiKey !== null) {
            $headers['api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listModelTypes
     *
     * Get all modelTypes.
     *
     * @param  int $page Current page *(Optional)* (optional)
     * @param  int $program_id Search on Program ID *(Optional)* (optional)
     * @param  int $broadcast_id Search on Broadcast ID *(Optional)* (optional)
     * @param  int $item_id Search on Item ID *(Optional)* (optional)
     * @param  int $campaign_id Search on Campaign ID *(Optional)* (optional)
     * @param  int $presenter_id Search on Presenter ID *(Optional)* (optional)
     * @param  int $contact_id Search on Contact ID *(Optional)* (optional)
     * @param  string $model Search Modeltypes for certain Model *(Optional)* (optional)
     * @param  int $limit Results per page *(Optional)* (optional)
     * @param  string $order_by Field to order the results *(Optional)* (optional)
     * @param  string $order_direction Direction of ordering *(Optional)* (optional)
     * @param  int $_external_station_id Query on a different (content providing) station *(Optional)* (optional)
     *
     * @throws \RadioManager\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \RadioManager\Model\ModelTypeResults
     */
    public function listModelTypes($page = null, $program_id = null, $broadcast_id = null, $item_id = null, $campaign_id = null, $presenter_id = null, $contact_id = null, $model = null, $limit = null, $order_by = null, $order_direction = null, $_external_station_id = null)
    {
        list($response) = $this->listModelTypesWithHttpInfo($page, $program_id, $broadcast_id, $item_id, $campaign_id, $presenter_id, $contact_id, $model, $limit, $order_by, $order_direction, $_external_station_id);
        return $response;
    }

    /**
     * Operation listModelTypesWithHttpInfo
     *
     * Get all modelTypes.
     *
     * @param  int $page Current page *(Optional)* (optional)
     * @param  int $program_id Search on Program ID *(Optional)* (optional)
     * @param  int $broadcast_id Search on Broadcast ID *(Optional)* (optional)
     * @param  int $item_id Search on Item ID *(Optional)* (optional)
     * @param  int $campaign_id Search on Campaign ID *(Optional)* (optional)
     * @param  int $presenter_id Search on Presenter ID *(Optional)* (optional)
     * @param  int $contact_id Search on Contact ID *(Optional)* (optional)
     * @param  string $model Search Modeltypes for certain Model *(Optional)* (optional)
     * @param  int $limit Results per page *(Optional)* (optional)
     * @param  string $order_by Field to order the results *(Optional)* (optional)
     * @param  string $order_direction Direction of ordering *(Optional)* (optional)
     * @param  int $_external_station_id Query on a different (content providing) station *(Optional)* (optional)
     *
     * @throws \RadioManager\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \RadioManager\Model\ModelTypeResults, HTTP status code, HTTP response headers (array of strings)
     */
    public function listModelTypesWithHttpInfo($page = null, $program_id = null, $broadcast_id = null, $item_id = null, $campaign_id = null, $presenter_id = null, $contact_id = null, $model = null, $limit = null, $order_by = null, $order_direction = null, $_external_station_id = null)
    {
        $returnType = '\RadioManager\Model\ModelTypeResults';
        $request = $this->listModelTypesRequest($page, $program_id, $broadcast_id, $item_id, $campaign_id, $presenter_id, $contact_id, $model, $limit, $order_by, $order_direction, $_external_station_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\RadioManager\Model\ModelTypeResults',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\RadioManager\Model\Forbidden',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\RadioManager\Model\NotFound',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\RadioManager\Model\TooManyRequests',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation listModelTypesAsync
     *
     * Get all modelTypes.
     *
     * @param  int $page Current page *(Optional)* (optional)
     * @param  int $program_id Search on Program ID *(Optional)* (optional)
     * @param  int $broadcast_id Search on Broadcast ID *(Optional)* (optional)
     * @param  int $item_id Search on Item ID *(Optional)* (optional)
     * @param  int $campaign_id Search on Campaign ID *(Optional)* (optional)
     * @param  int $presenter_id Search on Presenter ID *(Optional)* (optional)
     * @param  int $contact_id Search on Contact ID *(Optional)* (optional)
     * @param  string $model Search Modeltypes for certain Model *(Optional)* (optional)
     * @param  int $limit Results per page *(Optional)* (optional)
     * @param  string $order_by Field to order the results *(Optional)* (optional)
     * @param  string $order_direction Direction of ordering *(Optional)* (optional)
     * @param  int $_external_station_id Query on a different (content providing) station *(Optional)* (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listModelTypesAsync($page = null, $program_id = null, $broadcast_id = null, $item_id = null, $campaign_id = null, $presenter_id = null, $contact_id = null, $model = null, $limit = null, $order_by = null, $order_direction = null, $_external_station_id = null)
    {
        return $this->listModelTypesAsyncWithHttpInfo($page, $program_id, $broadcast_id, $item_id, $campaign_id, $presenter_id, $contact_id, $model, $limit, $order_by, $order_direction, $_external_station_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listModelTypesAsyncWithHttpInfo
     *
     * Get all modelTypes.
     *
     * @param  int $page Current page *(Optional)* (optional)
     * @param  int $program_id Search on Program ID *(Optional)* (optional)
     * @param  int $broadcast_id Search on Broadcast ID *(Optional)* (optional)
     * @param  int $item_id Search on Item ID *(Optional)* (optional)
     * @param  int $campaign_id Search on Campaign ID *(Optional)* (optional)
     * @param  int $presenter_id Search on Presenter ID *(Optional)* (optional)
     * @param  int $contact_id Search on Contact ID *(Optional)* (optional)
     * @param  string $model Search Modeltypes for certain Model *(Optional)* (optional)
     * @param  int $limit Results per page *(Optional)* (optional)
     * @param  string $order_by Field to order the results *(Optional)* (optional)
     * @param  string $order_direction Direction of ordering *(Optional)* (optional)
     * @param  int $_external_station_id Query on a different (content providing) station *(Optional)* (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listModelTypesAsyncWithHttpInfo($page = null, $program_id = null, $broadcast_id = null, $item_id = null, $campaign_id = null, $presenter_id = null, $contact_id = null, $model = null, $limit = null, $order_by = null, $order_direction = null, $_external_station_id = null)
    {
        $returnType = '\RadioManager\Model\ModelTypeResults';
        $request = $this->listModelTypesRequest($page, $program_id, $broadcast_id, $item_id, $campaign_id, $presenter_id, $contact_id, $model, $limit, $order_by, $order_direction, $_external_station_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listModelTypes'
     *
     * @param  int $page Current page *(Optional)* (optional)
     * @param  int $program_id Search on Program ID *(Optional)* (optional)
     * @param  int $broadcast_id Search on Broadcast ID *(Optional)* (optional)
     * @param  int $item_id Search on Item ID *(Optional)* (optional)
     * @param  int $campaign_id Search on Campaign ID *(Optional)* (optional)
     * @param  int $presenter_id Search on Presenter ID *(Optional)* (optional)
     * @param  int $contact_id Search on Contact ID *(Optional)* (optional)
     * @param  string $model Search Modeltypes for certain Model *(Optional)* (optional)
     * @param  int $limit Results per page *(Optional)* (optional)
     * @param  string $order_by Field to order the results *(Optional)* (optional)
     * @param  string $order_direction Direction of ordering *(Optional)* (optional)
     * @param  int $_external_station_id Query on a different (content providing) station *(Optional)* (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function listModelTypesRequest($page = null, $program_id = null, $broadcast_id = null, $item_id = null, $campaign_id = null, $presenter_id = null, $contact_id = null, $model = null, $limit = null, $order_by = null, $order_direction = null, $_external_station_id = null)
    {
        if ($page !== null && $page < 0) {
            throw new \InvalidArgumentException('invalid value for "$page" when calling ModelTypeApi.listModelTypes, must be bigger than or equal to 0.');
        }

        if ($limit !== null && $limit > 50) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling ModelTypeApi.listModelTypes, must be smaller than or equal to 50.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling ModelTypeApi.listModelTypes, must be bigger than or equal to 1.');
        }


        $resourcePath = '/model_types';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($page !== null) {
            $queryParams['page'] = ObjectSerializer::toQueryValue($page);
        }
        // query params
        if ($program_id !== null) {
            $queryParams['program_id'] = ObjectSerializer::toQueryValue($program_id);
        }
        // query params
        if ($broadcast_id !== null) {
            $queryParams['broadcast_id'] = ObjectSerializer::toQueryValue($broadcast_id);
        }
        // query params
        if ($item_id !== null) {
            $queryParams['item_id'] = ObjectSerializer::toQueryValue($item_id);
        }
        // query params
        if ($campaign_id !== null) {
            $queryParams['campaign_id'] = ObjectSerializer::toQueryValue($campaign_id);
        }
        // query params
        if ($presenter_id !== null) {
            $queryParams['presenter_id'] = ObjectSerializer::toQueryValue($presenter_id);
        }
        // query params
        if ($contact_id !== null) {
            $queryParams['contact_id'] = ObjectSerializer::toQueryValue($contact_id);
        }
        // query params
        if ($model !== null) {
            $queryParams['model'] = ObjectSerializer::toQueryValue($model);
        }
        // query params
        if ($limit !== null) {
            $queryParams['limit'] = ObjectSerializer::toQueryValue($limit);
        }
        // query params
        if ($order_by !== null) {
            $queryParams['order-by'] = ObjectSerializer::toQueryValue($order_by);
        }
        // query params
        if ($order_direction !== null) {
            $queryParams['order-direction'] = ObjectSerializer::toQueryValue($order_direction);
        }
        // query params
        if ($_external_station_id !== null) {
            $queryParams['_external_station_id'] = ObjectSerializer::toQueryValue($_external_station_id);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api-key');
        if ($apiKey !== null) {
            $headers['api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
