<?php
/**
 * ItemDataInputTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  RadioManager
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * RadioManager
 *
 * RadioManager
 *
 * OpenAPI spec version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace RadioManager;

/**
 * ItemDataInputTest Class Doc Comment
 *
 * @category    Class */
// * @description ItemDataInput
/**
 * @package     RadioManager
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ItemDataInputTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ItemDataInput"
     */
    public function testItemDataInput()
    {
    }

    /**
     * Test attribute "model_type_id"
     */
    public function testPropertyModelTypeId()
    {
    }

    /**
     * Test attribute "block_id"
     */
    public function testPropertyBlockId()
    {
    }

    /**
     * Test attribute "external_id"
     */
    public function testPropertyExternalId()
    {
    }

    /**
     * Test attribute "field_values"
     */
    public function testPropertyFieldValues()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {
    }

    /**
     * Test attribute "start"
     */
    public function testPropertyStart()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "import"
     */
    public function testPropertyImport()
    {
    }

    /**
     * Test attribute "campaign_id"
     */
    public function testPropertyCampaignId()
    {
    }

    /**
     * Test attribute "recommended"
     */
    public function testPropertyRecommended()
    {
    }

    /**
     * Test attribute "station_draft_id"
     */
    public function testPropertyStationDraftId()
    {
    }

    /**
     * Test attribute "program_draft_id"
     */
    public function testPropertyProgramDraftId()
    {
    }

    /**
     * Test attribute "user_draft_id"
     */
    public function testPropertyUserDraftId()
    {
    }

    /**
     * Test attribute "static_start"
     */
    public function testPropertyStaticStart()
    {
    }

    /**
     * Test attribute "details"
     */
    public function testPropertyDetails()
    {
    }

    /**
     * Test attribute "_previous_id"
     */
    public function testPropertyPreviousId()
    {
    }

    /**
     * Test attribute "_before_id"
     */
    public function testPropertyBeforeId()
    {
    }

    /**
     * Test attribute "contacts"
     */
    public function testPropertyContacts()
    {
    }

    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {
    }
}
