<?php
/**
 * StationResultStationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  RadioManager
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * RadioManager
 *
 * RadioManager
 *
 * OpenAPI spec version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace RadioManager;

/**
 * StationResultStationTest Class Doc Comment
 *
 * @category    Class */
// * @description StationResultStation
/**
 * @package     RadioManager
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StationResultStationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "StationResultStation"
     */
    public function testStationResultStation()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "system_name"
     */
    public function testPropertySystemName()
    {
    }

    /**
     * Test attribute "short_name"
     */
    public function testPropertyShortName()
    {
    }

    /**
     * Test attribute "medium_name"
     */
    public function testPropertyMediumName()
    {
    }

    /**
     * Test attribute "website"
     */
    public function testPropertyWebsite()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "keywords"
     */
    public function testPropertyKeywords()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "sms"
     */
    public function testPropertySms()
    {
    }

    /**
     * Test attribute "telephone"
     */
    public function testPropertyTelephone()
    {
    }

    /**
     * Test attribute "genre_id"
     */
    public function testPropertyGenreId()
    {
    }

    /**
     * Test attribute "language"
     */
    public function testPropertyLanguage()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "logo_rectangle"
     */
    public function testPropertyLogoRectangle()
    {
    }

    /**
     * Test attribute "logo_128x128"
     */
    public function testPropertyLogo128x128()
    {
    }

    /**
     * Test attribute "logo_320x320"
     */
    public function testPropertyLogo320x320()
    {
    }

    /**
     * Test attribute "logo_600x600"
     */
    public function testPropertyLogo600x600()
    {
    }

    /**
     * Test attribute "pay_off"
     */
    public function testPropertyPayOff()
    {
    }

    /**
     * Test attribute "pty_code"
     */
    public function testPropertyPtyCode()
    {
    }

    /**
     * Test attribute "pty_type"
     */
    public function testPropertyPtyType()
    {
    }

    /**
     * Test attribute "station_key"
     */
    public function testPropertyStationKey()
    {
    }

    /**
     * Test attribute "trial_date"
     */
    public function testPropertyTrialDate()
    {
    }
}
