<?php
/**
 * StationResultStationStartDaysTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  RadioManager
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * RadioManager
 *
 * RadioManager
 *
 * OpenAPI spec version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace RadioManager;

/**
 * StationResultStationStartDaysTest Class Doc Comment
 *
 * @category    Class */
// * @description StationResultStationStartDays
/**
 * @package     RadioManager
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StationResultStationStartDaysTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "StationResultStationStartDays"
     */
    public function testStationResultStationStartDays()
    {
    }

    /**
     * Test attribute "monday"
     */
    public function testPropertyMonday()
    {
    }

    /**
     * Test attribute "tuesday"
     */
    public function testPropertyTuesday()
    {
    }

    /**
     * Test attribute "wednesday"
     */
    public function testPropertyWednesday()
    {
    }

    /**
     * Test attribute "thursday"
     */
    public function testPropertyThursday()
    {
    }

    /**
     * Test attribute "friday"
     */
    public function testPropertyFriday()
    {
    }

    /**
     * Test attribute "saturday"
     */
    public function testPropertySaturday()
    {
    }

    /**
     * Test attribute "sunday"
     */
    public function testPropertySunday()
    {
    }
}
