<?php
/**
 * BlockApiTest
 * PHP version 5
 *
 * @category Class
 * @package  RadioManager
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * RadioManager
 *
 * RadioManager
 *
 * OpenAPI spec version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace RadioManager;

use \RadioManager\Configuration;
use \RadioManager\ApiClient;
use \RadioManager\ApiException;
use \RadioManager\ObjectSerializer;

/**
 * BlockApiTest Class Doc Comment
 *
 * @category Class
 * @package  RadioManager
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BlockApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getBlockById
     *
     * Get block by id.
     *
     */
    public function testGetBlockById()
    {
    }

    /**
     * Test case for getCurrentBlock
     *
     * Get current Block.
     *
     */
    public function testGetCurrentBlock()
    {
    }

    /**
     * Test case for getNextBlock
     *
     * Get upcoming Block.
     *
     */
    public function testGetNextBlock()
    {
    }

    /**
     * Test case for listBlocks
     *
     * Get a list of all blocks currently in your station..
     *
     */
    public function testListBlocks()
    {
    }
}
