<?php
/**
 * BroadcastApiTest
 * PHP version 5
 *
 * @category Class
 * @package  RadioManager
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Pluxbox Radiomanager Client
 *
 * Pluxbox RadioManager gives you the power, flexibility and speed you always wanted in a lightweight and easy-to-use web-based radio solution. With Pluxbox RadioManager you can organise your radio workflow and automate your omnichannel communication with your listeners. We offer wide range specialised services for the radio and connections like Hybrid Radio, Visual Radio, your website and social media without losing focus on your broadcast. For more information visit https://pluxbox.com
 *
 * OpenAPI spec version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace RadioManager;

use \RadioManager\Configuration;
use \RadioManager\ApiClient;
use \RadioManager\ApiException;
use \RadioManager\ObjectSerializer;

/**
 * BroadcastApiTest Class Doc Comment
 *
 * @category Class
 * @package  RadioManager
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BroadcastApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createBroadcast
     *
     * Create broadcast..
     *
     */
    public function testCreateBroadcast()
    {
    }

    /**
     * Test case for deleteBroadcastById
     *
     * Delete broadcast by id.
     *
     */
    public function testDeleteBroadcastById()
    {
    }

    /**
     * Test case for getBroadcastById
     *
     * Get broadcast by id.
     *
     */
    public function testGetBroadcastById()
    {
    }

    /**
     * Test case for getCurrentBroadcast
     *
     * Get current Broadcast.
     *
     */
    public function testGetCurrentBroadcast()
    {
    }

    /**
     * Test case for getDailyEPG
     *
     * Get daily EPG.
     *
     */
    public function testGetDailyEPG()
    {
    }

    /**
     * Test case for getEPGByDate
     *
     * Get EPG by date.
     *
     */
    public function testGetEPGByDate()
    {
    }

    /**
     * Test case for getNextBroadcast
     *
     * Get next Broadcast.
     *
     */
    public function testGetNextBroadcast()
    {
    }

    /**
     * Test case for getWeeklyEPG
     *
     * Get weekly EPG.
     *
     */
    public function testGetWeeklyEPG()
    {
    }

    /**
     * Test case for listBroadcasts
     *
     * Get all broadcasts..
     *
     */
    public function testListBroadcasts()
    {
    }

    /**
     * Test case for printBroadcastById
     *
     * Print Broadcast by id.
     *
     */
    public function testPrintBroadcastById()
    {
    }

    /**
     * Test case for updateBroadcastByID
     *
     * Update broadcast by id.
     *
     */
    public function testUpdateBroadcastByID()
    {
    }
}
